"""Generation utilities for image, video, and text generation.

This module provides utilities for working with diffusion models
including Stable Diffusion, SDXL, text generation sampling, and chat.

Examples:
    >>> from hf_gtc.generation import diffusers, sampling, chat
    >>> config = diffusers.create_generation_config(num_inference_steps=20)
    >>> config.num_inference_steps
    20
    >>> samp = sampling.create_sampling_config(temperature=0.7)
    >>> samp.temperature
    0.7
    >>> msg = chat.create_chat_message("user", "Hello!")
    >>> msg.content
    'Hello!'
"""

from __future__ import annotations

from hf_gtc.generation import chat, diffusers, prompting, prompts, tools
from hf_gtc.generation.chat import (
    VALID_MESSAGE_ROLES,
    VALID_TEMPLATE_FORMATS,
    VALID_TRUNCATION_STRATEGIES,
    ChatConfig,
    ChatMessage,
    ChatStats,
    ChatTemplateFormat,
    ConversationConfig,
    MessageRole,
    TemplateConfig,
    count_conversation_tokens,
    create_chat_config,
    create_chat_message,
    create_conversation_config,
    create_template_config,
    format_chat_prompt,
    get_message_role,
    get_template_format,
    list_message_roles,
    list_template_formats,
    validate_chat_config,
    validate_chat_message,
)
from hf_gtc.generation.prompting import (
    VALID_FEW_SHOT_STRATEGIES,
    VALID_PROMPT_FORMATS,
    VALID_REASONING_TYPES,
    CoTConfig,
    FewShotStrategy,
    PromptFormat,
    ReasoningType,
    add_cot_reasoning,
    build_complete_prompt,
    format_few_shot_examples,
    get_few_shot_strategy,
    get_prompt_format,
    get_reasoning_type,
    list_few_shot_strategies,
    list_prompt_formats,
    list_reasoning_types,
    validate_prompt_config,
)
from hf_gtc.generation.prompting import CoTConfig as PromptingCoTConfig
from hf_gtc.generation.prompting import FewShotConfig as PromptingFewShotConfig
from hf_gtc.generation.prompting import FewShotExample as PromptingFewShotExample
from hf_gtc.generation.prompting import PromptConfig as PromptingPromptConfig
from hf_gtc.generation.prompting import PromptStats as PromptingPromptStats
from hf_gtc.generation.prompting import PromptTemplate as PromptingPromptTemplate
from hf_gtc.generation.prompting import create_cot_config as create_prompting_cot_config
from hf_gtc.generation.prompting import (
    create_few_shot_config as create_prompting_few_shot_config,
)
from hf_gtc.generation.prompting import (
    create_few_shot_example as create_prompting_few_shot_example,
)
from hf_gtc.generation.prompting import (
    create_prompt_config as create_prompting_prompt_config,
)
from hf_gtc.generation.prompting import (
    create_prompt_stats as create_prompting_prompt_stats,
)
from hf_gtc.generation.prompting import (
    create_prompt_template as create_prompting_prompt_template,
)
from hf_gtc.generation.prompting import (
    estimate_prompt_tokens as estimate_prompting_tokens,
)
from hf_gtc.generation.prompting import format_prompt as format_prompting_prompt
from hf_gtc.generation.prompting import format_prompt_stats as format_prompting_stats
from hf_gtc.generation.prompting import (
    get_recommended_prompt_config as get_recommended_prompting_config,
)
from hf_gtc.generation.prompting import (
    truncate_prompt as truncate_prompt_by_length,
)
from hf_gtc.generation.prompting import (
    validate_cot_config as validate_prompting_cot_config,
)
from hf_gtc.generation.prompting import (
    validate_few_shot_config as validate_prompting_few_shot_config,
)
from hf_gtc.generation.prompting import (
    validate_prompt_template as validate_prompting_template,
)
from hf_gtc.generation.prompts import (
    VALID_PROMPT_ROLES,
    VALID_PROMPT_STYLES,
    VALID_SELECTION_STRATEGIES,
    ChainOfThoughtConfig,
    ExampleSelectionStrategy,
    FewShotConfig,
    FewShotExample,
    PromptConfig,
    PromptMessage,
    PromptRole,
    PromptStats,
    PromptStyle,
    PromptTemplate,
    SystemPromptConfig,
    build_conversation_prompt,
    create_cot_config,
    create_few_shot_config,
    create_few_shot_example,
    create_prompt_config,
    create_prompt_message,
    create_prompt_stats,
    create_prompt_template,
    create_system_prompt_config,
    estimate_prompt_tokens,
    format_cot_prompt,
    format_few_shot_prompt,
    format_messages,
    format_prompt,
    format_prompt_stats,
    format_system_prompt,
    get_prompt_role,
    get_prompt_style,
    get_recommended_prompt_config,
    get_selection_strategy,
    list_prompt_roles,
    list_prompt_styles,
    list_selection_strategies,
    truncate_prompt,
    validate_cot_config,
    validate_few_shot_config,
    validate_prompt_template,
    validate_system_prompt_config,
)
from hf_gtc.generation.sampling import (
    VALID_STOP_CRITERIA,
    VALID_STRATEGIES,
    BeamSearchConfig,
    ContrastiveConfig,
    GenerationConstraints,
    SamplingConfig,
    SamplingStrategy,
    StoppingCriteria,
    calculate_effective_vocab_size,
    create_beam_search_config,
    create_contrastive_config,
    create_generation_constraints,
    create_sampling_config,
    create_stopping_criteria,
    estimate_generation_memory,
    get_recommended_config,
    get_sampling_strategy,
    list_sampling_strategies,
    validate_beam_search_config,
    validate_generation_constraints,
    validate_sampling_config,
)
from hf_gtc.generation.structured import (
    VALID_OUTPUT_FORMATS,
    VALID_SCHEMA_TYPES,
    ChoicesConfig,
    GrammarConfig,
    JSONSchemaConfig,
    OutputFormat,
    SchemaType,
    StructuredConfig,
    ValidationResult,
    create_choices_config,
    create_grammar_config,
    create_json_schema_config,
    create_structured_config,
    create_validation_result,
    estimate_structured_tokens,
    format_validation_result,
    get_output_format,
    get_recommended_structured_config,
    get_schema_type,
    list_output_formats,
    list_schema_types,
    validate_choices_config,
    validate_grammar_config,
    validate_json_output,
    validate_json_schema_config,
    validate_structured_config,
)
from hf_gtc.generation.tools import (
    VALID_EXECUTION_MODES,
    VALID_PARSING_STRATEGIES,
    VALID_TOOL_FORMATS,
    ExecutionMode,
    ParsingStrategy,
    ToolCall,
    ToolConfig,
    ToolDefinition,
    ToolFormat,
    ToolResult,
    ToolStats,
    create_tool_call,
    create_tool_config,
    create_tool_definition,
    create_tool_result,
    create_tool_stats,
    execute_tool_calls,
    format_tool_stats,
    format_tools_for_prompt,
    get_execution_mode,
    get_parsing_strategy,
    get_recommended_tool_config,
    get_tool_format,
    list_execution_modes,
    list_parsing_strategies,
    list_tool_formats,
    parse_tool_calls,
    validate_tool_arguments,
    validate_tool_call,
    validate_tool_config,
    validate_tool_definition,
    validate_tool_result,
)

__all__: list[str] = [
    # Constants
    "VALID_EXECUTION_MODES",
    "VALID_FEW_SHOT_STRATEGIES",
    "VALID_MESSAGE_ROLES",
    "VALID_OUTPUT_FORMATS",
    "VALID_PARSING_STRATEGIES",
    "VALID_PROMPT_FORMATS",
    "VALID_PROMPT_ROLES",
    "VALID_PROMPT_STYLES",
    "VALID_REASONING_TYPES",
    "VALID_SCHEMA_TYPES",
    "VALID_SELECTION_STRATEGIES",
    "VALID_STOP_CRITERIA",
    "VALID_STRATEGIES",
    "VALID_TEMPLATE_FORMATS",
    "VALID_TOOL_FORMATS",
    "VALID_TRUNCATION_STRATEGIES",
    # Dataclasses/Enums
    "BeamSearchConfig",
    "ChainOfThoughtConfig",
    "ChatConfig",
    "ChatMessage",
    "ChatStats",
    "ChatTemplateFormat",
    "ChoicesConfig",
    "CoTConfig",
    "ContrastiveConfig",
    "ConversationConfig",
    "ExampleSelectionStrategy",
    "ExecutionMode",
    "FewShotConfig",
    "FewShotExample",
    "FewShotStrategy",
    "GenerationConstraints",
    "GrammarConfig",
    "JSONSchemaConfig",
    "MessageRole",
    "OutputFormat",
    "ParsingStrategy",
    "PromptConfig",
    "PromptFormat",
    "PromptMessage",
    "PromptRole",
    "PromptStats",
    "PromptStyle",
    "PromptTemplate",
    "PromptingCoTConfig",
    "PromptingFewShotConfig",
    "PromptingFewShotExample",
    "PromptingPromptConfig",
    "PromptingPromptStats",
    "PromptingPromptTemplate",
    "ReasoningType",
    "SamplingConfig",
    "SamplingStrategy",
    "SchemaType",
    "StoppingCriteria",
    "StructuredConfig",
    "SystemPromptConfig",
    "TemplateConfig",
    "ToolCall",
    "ToolConfig",
    "ToolDefinition",
    "ToolFormat",
    "ToolResult",
    "ToolStats",
    "ValidationResult",
    # Functions
    "add_cot_reasoning",
    "build_complete_prompt",
    "build_conversation_prompt",
    "calculate_effective_vocab_size",
    "chat",
    "count_conversation_tokens",
    "create_beam_search_config",
    "create_chat_config",
    "create_chat_message",
    "create_choices_config",
    "create_contrastive_config",
    "create_conversation_config",
    "create_cot_config",
    "create_few_shot_config",
    "create_few_shot_example",
    "create_generation_constraints",
    "create_grammar_config",
    "create_json_schema_config",
    "create_prompt_config",
    "create_prompt_message",
    "create_prompt_stats",
    "create_prompt_template",
    "create_prompting_cot_config",
    "create_prompting_few_shot_config",
    "create_prompting_few_shot_example",
    "create_prompting_prompt_config",
    "create_prompting_prompt_stats",
    "create_prompting_prompt_template",
    "create_sampling_config",
    "create_stopping_criteria",
    "create_structured_config",
    "create_system_prompt_config",
    "create_template_config",
    "create_tool_call",
    "create_tool_config",
    "create_tool_definition",
    "create_tool_result",
    "create_tool_stats",
    "create_validation_result",
    "diffusers",
    "estimate_generation_memory",
    "estimate_prompt_tokens",
    "estimate_prompting_tokens",
    "estimate_structured_tokens",
    "execute_tool_calls",
    "format_chat_prompt",
    "format_cot_prompt",
    "format_few_shot_examples",
    "format_few_shot_prompt",
    "format_messages",
    "format_prompt",
    "format_prompt_stats",
    "format_prompting_prompt",
    "format_prompting_stats",
    "format_system_prompt",
    "format_tool_stats",
    "format_tools_for_prompt",
    "format_validation_result",
    "get_execution_mode",
    "get_few_shot_strategy",
    "get_message_role",
    "get_output_format",
    "get_parsing_strategy",
    "get_prompt_format",
    "get_prompt_role",
    "get_prompt_style",
    "get_reasoning_type",
    "get_recommended_config",
    "get_recommended_prompt_config",
    "get_recommended_prompting_config",
    "get_recommended_structured_config",
    "get_recommended_tool_config",
    "get_sampling_strategy",
    "get_schema_type",
    "get_selection_strategy",
    "get_template_format",
    "get_tool_format",
    "list_execution_modes",
    "list_few_shot_strategies",
    "list_message_roles",
    "list_output_formats",
    "list_parsing_strategies",
    "list_prompt_formats",
    "list_prompt_roles",
    "list_prompt_styles",
    "list_reasoning_types",
    "list_sampling_strategies",
    "list_schema_types",
    "list_selection_strategies",
    "list_template_formats",
    "list_tool_formats",
    "parse_tool_calls",
    "prompting",
    "prompts",
    "tools",
    "truncate_prompt",
    "truncate_prompt_by_length",
    "validate_beam_search_config",
    "validate_chat_config",
    "validate_chat_message",
    "validate_choices_config",
    "validate_cot_config",
    "validate_few_shot_config",
    "validate_generation_constraints",
    "validate_grammar_config",
    "validate_json_output",
    "validate_json_schema_config",
    "validate_prompt_config",
    "validate_prompt_template",
    "validate_prompting_cot_config",
    "validate_prompting_few_shot_config",
    "validate_prompting_template",
    "validate_sampling_config",
    "validate_structured_config",
    "validate_system_prompt_config",
    "validate_tool_arguments",
    "validate_tool_call",
    "validate_tool_config",
    "validate_tool_definition",
    "validate_tool_result",
]
