"""Hub API recipes for HuggingFace model and dataset discovery.

This module provides utilities for searching, parsing, and interacting with
the HuggingFace Hub API, including models, datasets, Spaces, Collections,
Model Registry operations, and Experiment Tracking.

Examples:
    >>> from hf_gtc.hub import search_models, parse_model_card, search_spaces
    >>> # Results depend on network, so just verify import works
    >>> callable(search_models) and callable(parse_model_card)
    True
    >>> callable(search_spaces)
    True
    >>> from hf_gtc.hub import create_registry_config, register_model
    >>> callable(create_registry_config) and callable(register_model)
    True
    >>> from hf_gtc.hub import create_experiment_config, create_experiment_run
    >>> callable(create_experiment_config) and callable(create_experiment_run)
    True
"""

from __future__ import annotations

from hf_gtc.hub.cards import (
    ModelCard,
    ModelCardMetadata,
    ModelCardSection,
    ValidationResult,
    extract_model_description,
    get_model_card,
    list_model_card_sections,
    parse_model_card,
    validate_model_card,
)
from hf_gtc.hub.collections import (
    VALID_ITEM_TYPES,
    VALID_SORT_OPTIONS,
    VALID_THEMES,
    CollectionConfig,
    CollectionItem,
    CollectionItemType,
    CollectionMetadata,
    CollectionQuery,
    CollectionStats,
    CollectionTheme,
    calculate_collection_score,
    create_collection_config,
    create_collection_item,
    create_collection_query,
    create_collection_stats,
    format_collection_slug,
    get_item_type,
    list_item_types,
    list_sort_options,
    list_themes,
    validate_collection_config,
    validate_collection_item,
)
from hf_gtc.hub.experiments import (
    VALID_AGGREGATIONS,
    VALID_ARTIFACT_TYPES,
    VALID_STATUSES,
    ArtifactConfig,
    ArtifactType,
    ExperimentConfig,
    ExperimentRun,
    ExperimentStats,
    ExperimentStatus,
    MetricAggregation,
    MetricConfig,
    TrackingConfig,
    calculate_experiment_stats,
    compare_runs,
    create_artifact_config,
    create_experiment_config,
    create_experiment_run,
    create_metric_config,
    format_experiment_summary,
    get_aggregation,
    get_artifact_type,
    get_best_run,
    get_recommended_tracking_config,
    get_status,
    list_aggregations,
    list_artifact_types,
    list_statuses,
    log_artifact,
    log_metric,
    validate_artifact_config,
    validate_experiment_config,
    validate_experiment_run,
    validate_metric_config,
)
from hf_gtc.hub.registry import (
    VALID_STAGES,
    VALID_TRANSITION_ACTIONS,
    VALID_VERSIONING_SCHEMES,
    ModelStage,
    ModelVersion,
    RegistryConfig,
    RegistryStats,
    TransitionAction,
    TransitionRequest,
    VersioningScheme,
    clear_registry,
    compare_versions,
    create_model_version,
    create_registry_config,
    create_registry_stats,
    create_transition_request,
    format_registry_stats,
    get_model_version,
    get_recommended_registry_config,
    get_stage,
    get_transition_action,
    get_versioning_scheme,
    list_model_versions,
    list_stages,
    list_transition_actions,
    list_versioning_schemes,
    register_model,
    rollback_version,
    transition_stage,
    validate_model_version,
    validate_registry_config,
    validate_registry_stats,
    validate_transition_request,
)
from hf_gtc.hub.search import search_datasets, search_models
from hf_gtc.hub.spaces import (
    SpaceHardware,
    SpaceInfo,
    SpaceRuntime,
    SpaceSDK,
    SpaceStage,
    get_space_info,
    get_space_runtime,
    iter_spaces,
    list_hardware_tiers,
    list_sdks,
    search_spaces,
    validate_hardware,
    validate_sdk,
)

__all__: list[str] = [
    # Experiments
    "VALID_AGGREGATIONS",
    "VALID_ARTIFACT_TYPES",
    # Collections
    "VALID_ITEM_TYPES",
    "VALID_SORT_OPTIONS",
    # Registry
    "VALID_STAGES",
    "VALID_STATUSES",
    "VALID_THEMES",
    "VALID_TRANSITION_ACTIONS",
    "VALID_VERSIONING_SCHEMES",
    "ArtifactConfig",
    "ArtifactType",
    "CollectionConfig",
    "CollectionItem",
    "CollectionItemType",
    "CollectionMetadata",
    "CollectionQuery",
    "CollectionStats",
    "CollectionTheme",
    "ExperimentConfig",
    "ExperimentRun",
    "ExperimentStats",
    "ExperimentStatus",
    "MetricAggregation",
    "MetricConfig",
    # Cards
    "ModelCard",
    "ModelCardMetadata",
    "ModelCardSection",
    "ModelStage",
    "ModelVersion",
    "RegistryConfig",
    "RegistryStats",
    # Spaces
    "SpaceHardware",
    "SpaceInfo",
    "SpaceRuntime",
    "SpaceSDK",
    "SpaceStage",
    "TrackingConfig",
    "TransitionAction",
    "TransitionRequest",
    "ValidationResult",
    "VersioningScheme",
    "calculate_collection_score",
    "calculate_experiment_stats",
    "clear_registry",
    "compare_runs",
    "compare_versions",
    "create_artifact_config",
    "create_collection_config",
    "create_collection_item",
    "create_collection_query",
    "create_collection_stats",
    "create_experiment_config",
    "create_experiment_run",
    "create_metric_config",
    "create_model_version",
    "create_registry_config",
    "create_registry_stats",
    "create_transition_request",
    "extract_model_description",
    "format_collection_slug",
    "format_experiment_summary",
    "format_registry_stats",
    "get_aggregation",
    "get_artifact_type",
    "get_best_run",
    "get_item_type",
    "get_model_card",
    "get_model_version",
    "get_recommended_registry_config",
    "get_recommended_tracking_config",
    "get_space_info",
    "get_space_runtime",
    "get_stage",
    "get_status",
    "get_transition_action",
    "get_versioning_scheme",
    "iter_spaces",
    "list_aggregations",
    "list_artifact_types",
    "list_hardware_tiers",
    "list_item_types",
    "list_model_card_sections",
    "list_model_versions",
    "list_sdks",
    "list_sort_options",
    "list_stages",
    "list_statuses",
    "list_themes",
    "list_transition_actions",
    "list_versioning_schemes",
    "log_artifact",
    "log_metric",
    "parse_model_card",
    "register_model",
    "rollback_version",
    # Search
    "search_datasets",
    "search_models",
    "search_spaces",
    "transition_stage",
    "validate_artifact_config",
    "validate_collection_config",
    "validate_collection_item",
    "validate_experiment_config",
    "validate_experiment_run",
    "validate_hardware",
    "validate_metric_config",
    "validate_model_card",
    "validate_model_version",
    "validate_registry_config",
    "validate_registry_stats",
    "validate_sdk",
    "validate_transition_request",
]
