"""RAG (Retrieval-Augmented Generation) recipes for HuggingFace models.

This module provides utilities for building RAG systems including
document chunking, embedding, and retrieval patterns.

Examples:
    >>> from hf_gtc.rag import ChunkingStrategy, create_chunking_config
    >>> config = create_chunking_config(chunk_size=512, overlap=50)
    >>> config.chunk_size
    512
"""

from __future__ import annotations

from hf_gtc.rag.indexing import (
    VALID_BACKENDS,
    VALID_DISTANCE_FUNCTIONS,
    VALID_FAISS_INDEX_TYPES,
    ChromaConfig,
    DistanceFunction,
    FAISSConfig,
    FAISSIndexType,
    IndexConfig,
    IndexStats,
    SearchConfig,
    VectorStoreBackend,
    calculate_optimal_nlist,
    calculate_optimal_nprobe,
    create_chroma_config,
    create_faiss_config,
    create_index_config,
    create_index_stats,
    create_search_config,
    estimate_index_size,
    get_backend,
    get_distance_function,
    get_faiss_index_type,
    list_backends,
    list_distance_functions,
    list_faiss_index_types,
    validate_faiss_config,
    validate_search_config,
)
from hf_gtc.rag.reranking import (
    VALID_FUSION_METHODS,
    VALID_RERANKER_TYPES,
    FusionConfig,
    FusionMethod,
    HybridSearchConfig,
    RerankerConfig,
    RerankerResult,
    RerankerType,
    calculate_linear_fusion,
    calculate_rrf_score,
    create_fusion_config,
    create_hybrid_search_config,
    create_reranker_config,
    create_reranker_result,
    get_fusion_method,
    get_reranker_type,
    list_fusion_methods,
    list_reranker_types,
    validate_fusion_config,
    validate_hybrid_search_config,
    validate_reranker_config,
)
from hf_gtc.rag.retrieval import (
    VALID_CHUNKING_STRATEGIES,
    VALID_DISTANCE_METRICS,
    VALID_RETRIEVAL_METHODS,
    ChunkingConfig,
    ChunkingStrategy,
    ChunkResult,
    DistanceMetric,
    DocumentChunk,
    RAGConfig,
    RetrievalMethod,
    RetrievalResult,
    RetrievalStats,
    calculate_chunk_count,
    calculate_overlap_ratio,
    create_chunking_config,
    create_document_chunk,
    create_rag_config,
    create_retrieval_result,
    estimate_retrieval_latency,
    format_retrieval_stats,
    get_chunking_strategy,
    get_distance_metric,
    get_recommended_chunk_size,
    get_retrieval_method,
    list_chunking_strategies,
    list_distance_metrics,
    list_retrieval_methods,
    validate_chunking_config,
    validate_rag_config,
)

__all__: list[str] = [
    "VALID_BACKENDS",
    "VALID_CHUNKING_STRATEGIES",
    "VALID_DISTANCE_FUNCTIONS",
    "VALID_DISTANCE_METRICS",
    "VALID_FAISS_INDEX_TYPES",
    "VALID_FUSION_METHODS",
    "VALID_RERANKER_TYPES",
    "VALID_RETRIEVAL_METHODS",
    # indexing
    "ChromaConfig",
    # retrieval
    "ChunkResult",
    "ChunkingConfig",
    "ChunkingStrategy",
    "DistanceFunction",
    "DistanceMetric",
    "DocumentChunk",
    "FAISSConfig",
    "FAISSIndexType",
    "FusionConfig",
    "FusionMethod",
    "HybridSearchConfig",
    "IndexConfig",
    "IndexStats",
    "RAGConfig",
    "RerankerConfig",
    "RerankerResult",
    "RerankerType",
    "RetrievalMethod",
    "RetrievalResult",
    "RetrievalStats",
    "SearchConfig",
    "VectorStoreBackend",
    "calculate_chunk_count",
    "calculate_linear_fusion",
    "calculate_optimal_nlist",
    "calculate_optimal_nprobe",
    "calculate_overlap_ratio",
    "calculate_rrf_score",
    "create_chroma_config",
    "create_chunking_config",
    "create_document_chunk",
    "create_faiss_config",
    "create_fusion_config",
    "create_hybrid_search_config",
    "create_index_config",
    "create_index_stats",
    "create_rag_config",
    "create_reranker_config",
    "create_reranker_result",
    "create_retrieval_result",
    "create_search_config",
    "estimate_index_size",
    "estimate_retrieval_latency",
    "format_retrieval_stats",
    "get_backend",
    "get_chunking_strategy",
    "get_distance_function",
    "get_distance_metric",
    "get_faiss_index_type",
    "get_fusion_method",
    "get_recommended_chunk_size",
    "get_reranker_type",
    "get_retrieval_method",
    "list_backends",
    "list_chunking_strategies",
    "list_distance_functions",
    "list_distance_metrics",
    "list_faiss_index_types",
    "list_fusion_methods",
    "list_reranker_types",
    "list_retrieval_methods",
    "validate_chunking_config",
    "validate_faiss_config",
    "validate_fusion_config",
    "validate_hybrid_search_config",
    "validate_rag_config",
    "validate_reranker_config",
    "validate_search_config",
]
