"""RAG (Retrieval-Augmented Generation) recipes for HuggingFace models.

This module provides utilities for building RAG systems including
document chunking, embedding, and retrieval patterns.

Examples:
    >>> from hf_gtc.rag import ChunkingStrategy, create_chunking_config
    >>> config = create_chunking_config(chunk_size=512, overlap=50)
    >>> config.chunk_size
    512
"""

from __future__ import annotations

from hf_gtc.rag.chunking import (
    VALID_BOUNDARY_DETECTIONS,
    VALID_OVERLAP_TYPES,
    BoundaryDetection,
    ChunkConfig,
    OverlapType,
    SemanticChunkConfig,
    create_chunk_config,
    create_chunk_result,
    create_semantic_chunk_config,
    estimate_retrieval_quality,
    format_chunk_stats,
    get_boundary_detection,
    get_overlap_type,
    get_recommended_chunking_config,
    list_boundary_detections,
    list_overlap_types,
    optimize_chunk_size,
    validate_chunk_boundaries,
    validate_chunk_config,
    validate_chunk_result,
    validate_semantic_chunk_config,
)
from hf_gtc.rag.chunking import (
    VALID_CHUNKING_STRATEGIES as VALID_CHUNKING_STRATEGIES_V2,
)
from hf_gtc.rag.chunking import (
    ChunkingStrategy as ChunkingStrategyV2,
)
from hf_gtc.rag.chunking import (
    ChunkResult as ChunkResultV2,
)
from hf_gtc.rag.chunking import (
    calculate_chunk_count as calculate_chunk_count_v2,
)
from hf_gtc.rag.chunking import (
    get_chunking_strategy as get_chunking_strategy_v2,
)
from hf_gtc.rag.chunking import (
    list_chunking_strategies as list_chunking_strategies_v2,
)
from hf_gtc.rag.hybrid_search import (
    VALID_FUSION_METHODS as VALID_HS_FUSION_METHODS,
)
from hf_gtc.rag.hybrid_search import (
    VALID_RETRIEVAL_MODES,
    VALID_SPARSE_METHODS,
    BM25Config,
    HybridConfig,
    HybridSearchResult,
    HybridStats,
    RetrievalMode,
    SparseConfig,
    SparseMethod,
    calculate_bm25_score,
    create_bm25_config,
    create_hybrid_config,
    create_hybrid_search_result,
    create_sparse_config,
    format_hybrid_stats,
    fuse_rankings,
    get_recommended_hybrid_config,
    get_retrieval_mode,
    get_sparse_method,
    list_retrieval_modes,
    list_sparse_methods,
    optimize_fusion_weights,
    validate_bm25_config,
    validate_hybrid_config,
    validate_hybrid_search_result,
    validate_sparse_config,
)
from hf_gtc.rag.hybrid_search import (
    FusionMethod as HSFusionMethod,
)
from hf_gtc.rag.hybrid_search import (
    calculate_rrf_score as calculate_hs_rrf_score,
)
from hf_gtc.rag.hybrid_search import (
    get_fusion_method as get_hs_fusion_method,
)
from hf_gtc.rag.hybrid_search import (
    list_fusion_methods as list_hs_fusion_methods,
)
from hf_gtc.rag.indexing import (
    VALID_BACKENDS,
    VALID_DISTANCE_FUNCTIONS,
    VALID_FAISS_INDEX_TYPES,
    ChromaConfig,
    DistanceFunction,
    FAISSConfig,
    FAISSIndexType,
    IndexConfig,
    IndexStats,
    SearchConfig,
    VectorStoreBackend,
    calculate_optimal_nlist,
    calculate_optimal_nprobe,
    create_chroma_config,
    create_faiss_config,
    create_index_config,
    create_index_stats,
    create_search_config,
    estimate_index_size,
    get_backend,
    get_distance_function,
    get_faiss_index_type,
    list_backends,
    list_distance_functions,
    list_faiss_index_types,
    validate_faiss_config,
    validate_search_config,
)
from hf_gtc.rag.reranking import (
    VALID_FUSION_METHODS,
    VALID_RERANKER_TYPES,
    FusionConfig,
    FusionMethod,
    HybridSearchConfig,
    RerankerConfig,
    RerankerResult,
    RerankerType,
    calculate_linear_fusion,
    calculate_rrf_score,
    create_fusion_config,
    create_hybrid_search_config,
    create_reranker_config,
    create_reranker_result,
    get_fusion_method,
    get_reranker_type,
    list_fusion_methods,
    list_reranker_types,
    validate_fusion_config,
    validate_hybrid_search_config,
    validate_reranker_config,
)
from hf_gtc.rag.retrieval import (
    VALID_CHUNKING_STRATEGIES,
    VALID_DISTANCE_METRICS,
    VALID_RETRIEVAL_METHODS,
    ChunkingConfig,
    ChunkingStrategy,
    ChunkResult,
    DistanceMetric,
    DocumentChunk,
    RAGConfig,
    RetrievalMethod,
    RetrievalResult,
    RetrievalStats,
    calculate_chunk_count,
    calculate_overlap_ratio,
    create_chunking_config,
    create_document_chunk,
    create_rag_config,
    create_retrieval_result,
    estimate_retrieval_latency,
    format_retrieval_stats,
    get_chunking_strategy,
    get_distance_metric,
    get_recommended_chunk_size,
    get_retrieval_method,
    list_chunking_strategies,
    list_distance_metrics,
    list_retrieval_methods,
    validate_chunking_config,
    validate_rag_config,
)
from hf_gtc.rag.vectorstore import (
    VALID_DISTANCE_METRICS as VALID_VS_DISTANCE_METRICS,
)
from hf_gtc.rag.vectorstore import (
    VALID_INDEX_TYPES,
    VALID_STORE_TYPES,
    IndexType,
    SearchResult,
    VectorStoreConfig,
    VectorStoreType,
    calculate_index_size,
    calculate_recall_at_k,
    create_search_result,
    create_vectorstore_config,
    estimate_search_latency,
    format_search_stats,
    get_index_type,
    get_recommended_vectorstore_config,
    get_store_type,
    list_index_types,
    list_store_types,
    optimize_index_params,
    validate_search_result,
    validate_vectorstore_config,
)
from hf_gtc.rag.vectorstore import (
    DistanceMetric as VSDistanceMetric,
)
from hf_gtc.rag.vectorstore import (
    IndexConfig as VSIndexConfig,
)
from hf_gtc.rag.vectorstore import (
    create_index_config as create_vs_index_config,
)
from hf_gtc.rag.vectorstore import (
    get_distance_metric as get_vs_distance_metric,
)
from hf_gtc.rag.vectorstore import (
    list_distance_metrics as list_vs_distance_metrics,
)
from hf_gtc.rag.vectorstore import (
    validate_index_config as validate_vs_index_config,
)

__all__: list[str] = [
    # Constants
    "VALID_BACKENDS",
    "VALID_BOUNDARY_DETECTIONS",
    "VALID_CHUNKING_STRATEGIES",
    "VALID_CHUNKING_STRATEGIES_V2",
    "VALID_DISTANCE_FUNCTIONS",
    "VALID_DISTANCE_METRICS",
    "VALID_FAISS_INDEX_TYPES",
    "VALID_FUSION_METHODS",
    "VALID_HS_FUSION_METHODS",
    "VALID_INDEX_TYPES",
    "VALID_OVERLAP_TYPES",
    "VALID_RERANKER_TYPES",
    "VALID_RETRIEVAL_METHODS",
    "VALID_RETRIEVAL_MODES",
    "VALID_SPARSE_METHODS",
    "VALID_STORE_TYPES",
    "VALID_VS_DISTANCE_METRICS",
    # Hybrid Search
    "BM25Config",
    # Chunking (v2)
    "BoundaryDetection",
    # Indexing
    "ChromaConfig",
    "ChunkConfig",
    "ChunkResult",
    "ChunkResultV2",
    # Retrieval
    "ChunkingConfig",
    "ChunkingStrategy",
    "ChunkingStrategyV2",
    "DistanceFunction",
    "DistanceMetric",
    "DocumentChunk",
    "FAISSConfig",
    "FAISSIndexType",
    # Reranking
    "FusionConfig",
    "FusionMethod",
    "HSFusionMethod",
    "HybridConfig",
    "HybridSearchConfig",
    "HybridSearchResult",
    "HybridStats",
    "IndexConfig",
    "IndexStats",
    # Vectorstore
    "IndexType",
    "OverlapType",
    "RAGConfig",
    "RerankerConfig",
    "RerankerResult",
    "RerankerType",
    "RetrievalMethod",
    "RetrievalMode",
    "RetrievalResult",
    "RetrievalStats",
    "SearchConfig",
    "SearchResult",
    "SemanticChunkConfig",
    "SparseConfig",
    "SparseMethod",
    "VSDistanceMetric",
    "VSIndexConfig",
    "VectorStoreBackend",
    "VectorStoreConfig",
    "VectorStoreType",
    "calculate_bm25_score",
    "calculate_chunk_count",
    "calculate_chunk_count_v2",
    "calculate_hs_rrf_score",
    "calculate_index_size",
    "calculate_linear_fusion",
    "calculate_optimal_nlist",
    "calculate_optimal_nprobe",
    "calculate_overlap_ratio",
    "calculate_recall_at_k",
    "calculate_rrf_score",
    "create_bm25_config",
    "create_chroma_config",
    "create_chunk_config",
    "create_chunk_result",
    "create_chunking_config",
    "create_document_chunk",
    "create_faiss_config",
    "create_fusion_config",
    "create_hybrid_config",
    "create_hybrid_search_config",
    "create_hybrid_search_result",
    "create_index_config",
    "create_index_stats",
    "create_rag_config",
    "create_reranker_config",
    "create_reranker_result",
    "create_retrieval_result",
    "create_search_config",
    "create_search_result",
    "create_semantic_chunk_config",
    "create_sparse_config",
    "create_vectorstore_config",
    "create_vs_index_config",
    "estimate_index_size",
    "estimate_retrieval_latency",
    "estimate_retrieval_quality",
    "estimate_search_latency",
    "format_chunk_stats",
    "format_hybrid_stats",
    "format_retrieval_stats",
    "format_search_stats",
    "fuse_rankings",
    "get_backend",
    "get_boundary_detection",
    "get_chunking_strategy",
    "get_chunking_strategy_v2",
    "get_distance_function",
    "get_distance_metric",
    "get_faiss_index_type",
    "get_fusion_method",
    "get_hs_fusion_method",
    "get_index_type",
    "get_overlap_type",
    "get_recommended_chunk_size",
    "get_recommended_chunking_config",
    "get_recommended_hybrid_config",
    "get_recommended_vectorstore_config",
    "get_reranker_type",
    "get_retrieval_method",
    "get_retrieval_mode",
    "get_sparse_method",
    "get_store_type",
    "get_vs_distance_metric",
    "list_backends",
    "list_boundary_detections",
    "list_chunking_strategies",
    "list_chunking_strategies_v2",
    "list_distance_functions",
    "list_distance_metrics",
    "list_faiss_index_types",
    "list_fusion_methods",
    "list_hs_fusion_methods",
    "list_index_types",
    "list_overlap_types",
    "list_reranker_types",
    "list_retrieval_methods",
    "list_retrieval_modes",
    "list_sparse_methods",
    "list_store_types",
    "list_vs_distance_metrics",
    "optimize_chunk_size",
    "optimize_fusion_weights",
    "optimize_index_params",
    "validate_bm25_config",
    "validate_chunk_boundaries",
    "validate_chunk_config",
    "validate_chunk_result",
    "validate_chunking_config",
    "validate_faiss_config",
    "validate_fusion_config",
    "validate_hybrid_config",
    "validate_hybrid_search_config",
    "validate_hybrid_search_result",
    "validate_rag_config",
    "validate_reranker_config",
    "validate_search_config",
    "validate_search_result",
    "validate_semantic_chunk_config",
    "validate_sparse_config",
    "validate_vectorstore_config",
    "validate_vs_index_config",
]
